import React from "react";
import { NavIcon } from "../navIcons.jsx";

function safeDisplay(value) { if (value === null || value === undefined) return ""; if (typeof value === "string" || typeof value === "number" || typeof value === "boolean") return String(value); if (Array.isArray(value)) return value.map(safeDisplay).join(", "); try { return JSON.stringify(value); } catch { return String(value); } }

export function Panel({ title, children }) { return <section className="antro-panel border border-orange-800 bg-black/80 mb-4"><h2 className="antro-panel-title bg-[#240B02] border-b border-orange-800 px-3 py-1 text-orange-300 font-bold tracking-wide">{title}</h2><div className="antro-panel-body p-3">{children}</div></section>; }
function renderCellValue(value) { if (value === null || value === undefined) return ""; if (React.isValidElement && React.isValidElement(value)) return value; if (Array.isArray(value)) return value.map((v, i) => <span key={i}>{renderCellValue(v)}{i < value.length - 1 ? ", " : ""}</span>); if (typeof value === "object") return safeDisplay(value); return safeDisplay(value); }
export function OldTable({ rows }) { const safeRows = Array.isArray(rows) ? rows : []; return <table className="antro-table w-full text-sm border-collapse"><tbody>{safeRows.map((row, i) => { const label = Array.isArray(row) ? row[0] : `Row ${i + 1}`; const value = Array.isArray(row) ? row[1] : row; return <tr key={`${String(label)}-${i}`} className="border-b border-orange-950/80"><td className="bg-[#240B02] px-2 py-1 text-orange-300">{renderCellValue(label)}</td><td className="bg-[#160701] px-2 py-1 text-right text-orange-100">{renderCellValue(value)}</td></tr>; })}</tbody></table>; }
export function TextInput({ value, onChange, className = "w-24", placeholder = "", onEnter = null }) { return <input className={`${className} bg-black border border-orange-900 text-orange-100 text-right px-1`} value={value} placeholder={placeholder} onChange={(e) => onChange(e.target.value)} onKeyDown={(e) => { if (e.key === "Enter" && onEnter) onEnter(e); }} />; }
export function MenuButton({ label, page, current, setPage, activeTone = "classic", icon = null, originalLabel = null }) { const active = current === page; const activeClass = activeTone === "identity" ? "bg-red-900/80 border-red-300 text-red-100" : "bg-orange-900/70 border-orange-300 text-orange-100"; const hasIcon = Boolean(icon); return <button className={`antro-action-btn ${hasIcon ? "antro-lhs-nav-item" : ""} px-2 py-1 border text-xs md:text-sm ${active ? activeClass : "bg-black border-orange-800 text-orange-400 hover:text-orange-100"}`} title={originalLabel && originalLabel !== label ? `${originalLabel} → ${label}` : undefined} onClick={() => setPage(page)}>{hasIcon && <NavIcon name={icon} />}<span className={hasIcon ? "antro-lhs-nav-label" : ""}>{label}</span></button>; }
