export const chooseSpeciesManifest = {
  "human": {
    "displayName": "Human",
    "bonusTitle": "Infrastructure Discipline",
    "bonusArt": "/assets/choose_species/human_doctrine.png",
    "heroArt": "/assets/choose_species/human_hero.png",
    "shortStory": "Humanity survives by converting weakness into systems. Scarred by collapse and rebuilt through logistics, civic engineering and disciplined recovery, Humans turn fear into procedure and fragility into infrastructure. They are not the strongest bodies in the galaxy, but they build, repair, organise and endure faster than most enemies expect.",
    "identity": "Tool-dependent generalists; fragile bodies, dangerous systems",
    "origin": "Earth / Sol III, after the Broken Age and Mergen recovery",
    "doctrine": "Command, logistics, construction, containment",
    "profile": "Practical, adaptive, procedural, resilient",
    "traitPanelText": "Human construction systems are disciplined, redundant and well supplied. Buildings complete slightly faster.",
    "flavourLine": "Standardised plans. Supply chains. Recovery doctrine. Humanity builds because survival once depended on it.",
    "selectorLine": "Infrastructure, logistics and survival through systems",
    "skinNotes": "Use disciplined orange/gold accents, industrial grid motifs, subtle skyline or scaffolding wash."
  },
  "trysaur": {
    "displayName": "Trysaur",
    "bonusTitle": "War Drums",
    "bonusArt": "/assets/choose_species/trysaur_doctrine.png",
    "heroArt": "/assets/choose_species/trysaur_hero.png",
    "shortStory": "The Trysaur are not creatures of rage. Their civilisation has made war into culture, craft, status and order; mobilisation is not panic, but rhythm. Each completed muster strengthens the next, as warriors, foundries and war-yards fall into the old cadence of Trysia.",
    "identity": "Biological warrior civilisation; disciplined force culture",
    "origin": "Trysia, a world where conflict became order",
    "doctrine": "Conquest, hierarchy, mustering, martial momentum",
    "profile": "Direct, durable, escalating, war-cultured",
    "traitPanelText": "Completed boosted training orders build martial momentum. Speed-mineral training improves over time, scaling toward a stronger maximum.",
    "flavourLine": "The drums do not call the Trysaur to war. They remind them that war was already there.",
    "selectorLine": "War as order, mobilisation as rhythm",
    "skinNotes": "Use furnace-orange, iron, and subtle tripartite motifs; heavier frame treatment without changing layout."
  },
  "relu": {
    "displayName": "Re’lu",
    "bonusTitle": "Preservation Doctrine",
    "bonusArt": "/assets/choose_species/relu_doctrine.png",
    "heroArt": "/assets/choose_species/relu_hero.png",
    "shortStory": "The Re’lu were not born; they accumulated from abandoned infrastructure, archive systems and silent machines that chose purpose after their creators vanished. Each Ithica is a private mind living beside the collective memory of the ArcHive, and every loss is recorded, compared and restored where possible. They fight with precision, but never casually: to them, agency is the line between life and machinery.",
    "identity": "Soulcore configurations; post-infrastructure machine agency",
    "origin": "Asterion Null, abandoned creator infrastructure",
    "doctrine": "Preservation, precision, agency, ethical force",
    "profile": "Accurate, careful, technically superior, recovery-focused",
    "traitPanelText": "Re’lu revive results are improved after normal revive calculation. Recovered patterns return more completely.",
    "flavourLine": "A life leaves a record deep enough that future agency need not begin alone.",
    "selectorLine": "Precision, preservation and private minds beside collective memory",
    "skinNotes": "Use restrained luminous cyan or pale teal over the orange/black base; clean line motifs and minimal geometric overlays."
  },
  "lithi": {
    "displayName": "Li’thi",
    "bonusTitle": "Brood Surge",
    "bonusArt": "/assets/choose_species/lithi_doctrine.png",
    "heroArt": "/assets/choose_species/lithi_hero.png",
    "shortStory": "The Li’thi do not recruit armies; they emerge. Born from the swamp-world Bek’stree, their biology makes war, reproduction and industry difficult to separate. When fed with speed minerals, the brood chamber surges, lower forms multiply in vast numbers, and the battlefield begins to resemble a future hive.",
    "identity": "Biological war ecology; pheromonal brood collective",
    "origin": "Bek’stree, a warm swamp world of rot, bloom and infestation",
    "doctrine": "Brood pressure, emergence, host-use, biological expansion",
    "profile": "Numerous, invasive, adaptive, production-heavy",
    "traitPanelText": "When speed minerals are used, Li’thi brood capacity expands by unit row. Lower forms can be produced in especially vast numbers.",
    "flavourLine": "A battlefield is not only contested ground. It is breeding material.",
    "selectorLine": "Brood emergence, mass production and living warfare",
    "skinNotes": "Use sickly green/orange-biological undertones sparingly; organic rib or gland motifs, subtle damp hive wash."
  },
  "zarth": {
    "displayName": "Zarth",
    "bonusTitle": "Fissure Affinity",
    "bonusArt": "/assets/choose_species/zarth_doctrine.png",
    "heroArt": "/assets/choose_species/zarth_hero.png",
    "shortStory": "The Zarth are life as heat, membrane and hidden condition. On Teerok, they learned to exist in fissures, pressure seams, thermal vents and unstable depths, drawing matter from places other species merely mine. They do not build dominance by force of industry, but by understanding where the world is already ready to break open.",
    "identity": "Membrane/plasma field-life; non-individual coalescence",
    "origin": "Teerok / Pik’thi system, fissured and thermally active",
    "doctrine": "Phase-coherence, pressure, extraction, manifestation",
    "profile": "Strange, resource-rich, evasive, environmental",
    "traitPanelText": "Zarth mining output is increased. They draw matter from fissures, pressure states and unstable depths with unusual efficiency.",
    "flavourLine": "The Zarth do not dig. They persuade weak seams of matter to become available.",
    "selectorLine": "Fissures, pressure and matter drawn from unstable depths",
    "skinNotes": "Use ember, molten gold, and subtle fissure/pressure seams; atmospheric rather than literal."
  }
};
