export const recordsFeaturedManifest = [
  {
    key: "broken_spear_turned_away",
    displayName: "Broken Spear — Turned Away",
    family: "broken_spear",
    perspective: "Attacking loss",
    band: "0–10",
    status: "draft",
    usage: "Earned archive / records-view artwork. Not for live battle reports yet.",
    description: "A failed offensive preserved as an archive plate: disciplined resistance, spent momentum, and a spear turned aside before it could find purchase.",
    art: "/assets/library/records/featured/broken_spear_turned_away_full.webp",
    sourcePlate: "/assets/library/records/featured/attack_defense_source_plate.webp",
  },
  {
    key: "the_fall_overrun",
    displayName: "The Fall — Overrun",
    family: "the_fall",
    perspective: "Defending loss",
    band: "0–10",
    status: "draft",
    usage: "Earned archive / records-view artwork. Not for live battle reports yet.",
    description: "A defensive collapse preserved as an archive plate: breached perimeter, overwhelmed lines, and the final shape of a position that could not hold.",
    art: "/assets/library/records/featured/the_fall_overrun_full.webp",
    sourcePlate: "/assets/library/records/featured/attack_defense_source_plate.webp",
  },
];
